# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

source 'https://github.com/card-io/card.io-iOS-SDK.git'

target 'ASDKSampleApp' do

pod 'CardIO'

end

