# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# use_frameworks!

platform :ios, '9.0'

target 'ASDKSampleApp' do

pod 'CardIO'
pod 'ASDKCore', :path => "../"
pod 'ASDKUI', :path => "../"

end

